### ISSUE TITLE
No logout button

### ISSUE THREAD

**Issue by billhowe** [uwescience/sqlshare#32] opened 2014-02-14 00:41 UTC
There's no way to logout from SQLShare.  You have to clear your browser cache.

**Comment by dhalperi** [comment] 2014-02-14 00:43
Duplicate of #3 . ;)

**Closed as completed by dhalperi** 2014-02-14 00:43 UTC
Labels: duplicate

**Comment by billhowe** [comment] 2014-02-14 05:56
Ya, github search failed me again. I should have just scanned through them
all manually.
